import Providers from '@/components/providers'
import '../styles/globals.css'

import { Footer } from '@/components/shared/footer'
import { Header } from '@/components/shared/header'
import { cn } from '@/lib/utils'
import { fontSans } from '@/styles/fonts'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={cn(fontSans.variable)}>
        <Providers>
          <div className="flex flex-col">
            <Header />
            <div className="flex-1 py-16">{children}</div>
            <Footer />
          </div>
        </Providers>
      </body>
    </html>
  )
}
