import '../styles/globals.css'

import { Footer } from '@/components/shared/footer'
import { Header } from '@/components/shared/header'
import { cn } from '@/lib/utils'
import Providers from '@/providers'
import { fontSans } from '@/styles/fonts'
import type { Metadata } from 'next'
import NextTopLoader from 'nextjs-toploader'

export const metadata: Metadata = {
  title: {
    default: 'FSW Store',
    template: '%s | FSW Store',
  },
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt" suppressHydrationWarning>
      <body className={cn(fontSans.variable)}>
        <NextTopLoader
          height={3}
          color="#4f32c3"
          easing="cubic-bezier(0.53,0.21,0,1)"
        />
        <Providers>
          <div className="flex min-h-full flex-col">
            <Header />
            <div className="flex-1">{children}</div>
            <Footer />
          </div>
        </Providers>
      </body>
    </html>
  )
}
